development:
  clients:
    default:
      database: contenido_boe_development
      hosts:
        - localhost:27017
      options:
  options:

test:
  clients:
    default:
      database: <%= ENV['mongoid_database'] %>
      username: <%= ENV['mongoid_username'] %>
      password: <%= ENV['mongoid_password'] %>
      hosts:
        - <%= ENV['mongoid_host'] %>:<%= ENV['mongoid_port'] %>
      options:
        read:
          mode: :primary
        max_pool_size: 1

