defaults: &defaults
  host: localhost
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

development:
  clients:
    default:
      database: contenido_boe_development
      hosts:
        - localhost:27017
      options:
  options:

test:
  clients:
    default:
      database: contenido_boe_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1

# set these environment variables on your prod server
production:
  host: <%= ENV['mongoid_host'] %>
  port: <%= ENV['mongoid_port'] %>
  username: <%= ENV['mongoid_username'] %>
  password: <%= ENV['mongoid_password'] %>
  database: <%= ENV['mongoid_database'] %>
