# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c7eb1337f60297bb8b5c92d5b0a941cf1e16752c547e957a03d237a262e55548c00b7effc5ab5f29b23b14903ce3cd3e93c8be6c84227f48fa8bafafe24a8e8

test:
  secret_key_base: 86bb124a37b1f6e4ad68b5faa6b9424f4d9eacedbf24b9901e490cddf0ec460f29f89deed4f56bc08fd8ac167791cd00d2dac43c4c17b04b142034faa9bfd939

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
